### ISSUE TITLE
Ambiguous references to ../vendor/autoload.php

### ISSUE THREAD

**Issue by mystica555** [funkatron/inspekt#11]
I'm curious where these references are actually pointing to.. 

Interestingly enough, I happen to have a 'vendor/autoload.php' from authorize.net sdk, but I somehow don't think this is what you're referring to?

html/inspekt/Examples# grep vendor *
config.php:require_once dirname(__FILE__) . "/../vendor/autoload.php";
db_escaping.php:require_once dirname(__FILE__) . "/../vendor/autoload.php";
extending.php:require_once dirname(__FILE__) . "/../vendor/autoload.php";
filter_array_cage.php:require_once dirname(__FILE__) . "/../vendor/autoload.php";
filter_form_input.php:require_once dirname(__FILE__) . "/../vendor/autoload.php";
filter_static_methods.php:require_once dirname(__FILE__) . "/../vendor/autoload.php";
filter_superglobals.php:require_once dirname(__FILE__) . "/../vendor/autoload.php";
formtest.php:require_once dirname(__FILE__) . "/../vendor/autoload.php";
get_or_post.php:require_once dirname(__FILE__) . "/../vendor/autoload.php";
htmlpurifier.php:require_once dirname(__FILE__) . "/../vendor/autoload.php";
iterate_cage.php:require_once dirname(__FILE__) . "/../vendor/autoload.php";
supercage.php:require_once dirname(__FILE__) . "/../vendor/autoload.php";
uri_tester.php:require_once dirname(__FILE__) . "/../vendor/autoload.php";

**Comment by lcherone** [comment]
Its referencing composers autoloader, most vendors will add a installation section in readme, but generally most consumers will see `vendor/autoload.php` and know is a composer package.

Install with composer:
`composer require funkatron/inspekt`

**Comment by funkatron** [comment]
Thanks for answering, @lcherone!
