### ISSUE TITLE
keyExists, getInt and getRaw fail when value to get is equal to zero

### ISSUE THREAD

**Issue by kenshin23** [funkatron/inspekt#5]
I'm trying to validate a form using Inspekt. One of the fields I'm trying to validate is a select box with values such as -1, 0, 1, 2, etc. I have set -1 as my invalid case, and all other cases are valid. However, when trying to get the value of the select, it works for any value except 0, which makes all of the above mentioned methods to fail (i.e.: return false).

I found it weird, so I thought I would mention it here. Any ideas?

**Comment by funkatron** [comment]
FYI I've added tests, and in 0.6.0 it seems to work:

```php
$inputarray['zeroint'] = 0;
// ............................
$this->assertSame(0, $this->cage->getRaw('zeroint'));
```
